import fs from 'fs';
import path from 'path';
import os from 'os';

export interface SessionMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

/**
 * Parse a Claude Code session file to extract conversation history
 */
export function parseSessionHistory(sessionId: string, repositoryPath: string): SessionMessage[] {
  const claudeProjectsDir = path.join(os.homedir(), '.claude', 'projects');
  const encodedPath = repositoryPath.replace(/\//g, '-');
  const sessionFilePath = path.join(claudeProjectsDir, encodedPath, `${sessionId}.jsonl`);

  if (!fs.existsSync(sessionFilePath)) {
    return [];
  }

  const content = fs.readFileSync(sessionFilePath, 'utf-8');
  const lines = content.trim().split('\n').filter(line => line.trim());

  const messages: SessionMessage[] = [];

  for (const line of lines) {
    try {
      const entry = JSON.parse(line);

      // User messages
      if (entry.type === 'user' && entry.message?.role === 'user') {
        // Extract text content (content could be string or object)
        const textContent = typeof entry.message.content === 'string'
          ? entry.message.content
          : extractTextContent(entry.message.content);

        // Filter out command/system messages and CLI caveats
        const isSystemMessage =
          textContent.includes('<local-command-') ||
          textContent.includes('<command-') ||
          textContent.includes('<output>') ||
          textContent.includes('Caveat: The messages below were generated by the user while running local commands') ||
          textContent.includes('No response requested');

        if (textContent && !isSystemMessage) {
          messages.push({
            role: 'user',
            content: textContent,
            timestamp: entry.timestamp
          });
        }
      }

      // Assistant messages
      if (entry.type === 'assistant' && entry.message?.role === 'assistant') {
        // Extract text content from content blocks
        const textContent = extractTextContent(entry.message.content);

        // Filter out system messages and CLI caveats
        const isSystemMessage =
          textContent.includes('<local-command-') ||
          textContent.includes('<command-') ||
          textContent.includes('<output>') ||
          textContent.includes('Caveat: The messages below were generated by the user while running local commands') ||
          textContent.includes('No response requested');

        if (textContent && !isSystemMessage) {
          messages.push({
            role: 'assistant',
            content: textContent,
            timestamp: entry.timestamp
          });
        }
      }
    } catch {
      // Skip malformed lines
      continue;
    }
  }

  return messages;
}

/**
 * Extract text content from Claude's content blocks
 * Content can be a string, object, or array of objects with type: 'text'
 */
function extractTextContent(content: unknown): string {
  if (typeof content === 'string') {
    return content;
  }

  if (Array.isArray(content)) {
    const textBlocks = content
      .filter((block: { type?: string; text?: string }) =>
        block.type === 'text' && block.text
      )
      .map((block: { text: string }) => block.text);

    return textBlocks.join('\n');
  }

  // Handle single content object
  if (content && typeof content === 'object' && 'type' in content && 'text' in content) {
    const block = content as { type: string; text: string };
    if (block.type === 'text' && block.text) {
      return block.text;
    }
  }

  return '';
}
